#!/bin/bash

# Algorithm for making template of Bash scripts

standard_use () {

	local cmd_use=$1
	local name_script=$2

	if [ $# -ne 0 ] && [ -n "$name_script" ]; then
		if [ -f "$name_script" ]; then
			$cmd_use "$name_script"
			return
		fi
		echo -e "#!/bin/bash\n\n# $name_script\n\n" > "$name_script"
		chmod +x "$name_script"
		$cmd_use "$name_script"
	else
		echo "Script must have a name."
	fi
	return

}

print_info () {

	cat <<- _EOF_

		Usage: mscript [OPTION]... [FILE]
		Create script with sheband "#/bin/bash"
		Set mode to execute the file
		Launch script with certain file editor (vim by default)

		Options:
			-h, --help					show help information
			-c, --copy FILE					copy text of script from another file
			-p, --partially-copy FILE			copy text of script from another file without name and shebang 		
			-e, --editor EDITOR				use certain editor

	_EOF_
	return
}

input_handle () {

	local name_editor="vim"
	local name_script=
	local name_copy=
	local -A executed_ops=(
		["copy"]=0
		["editor"]=0
	)

	while [[ -n "$1" ]]; do
		case "$1" in
			-h | --help)						print_info
															return
															;;

			-c | --copy)						if (( executed_ops["copy"] == 0 )); then
																executed_ops["copy"]=1
																shift
																if [ -n "$1" ]; then
																	name_copy="$1"
																else
																	echo "You should specify the name of file you want to copy" >&2
																	exit 1
																fi
																if [ ! -f "$1" ]; then
																	echo "The file you want to copy doesn't exist" >&2
																	exit 1
																fi
															fi
															;;

			-p | --partially-copy)	if (( executed_ops["copy"] == 0 )); then
																executed_ops["copy"]=2
																shift
																if [ -n "$1" ]; then
																	name_copy="$1"
																else
																	echo "You should specify the name of file you want to copy" >&2
																	exit 1
																fi
																if [ ! -f "$1" ]; then
																	echo "The file you want to copy doesn't exist" >&2
																	exit 1
																fi
															fi
															;;

			-e | --editor)					if (( executed_ops["editor"] == 0 )); then
																executed_ops["editor"]=1
																shift
																if [ -n "$1" ]; then
																	if command -v "$1" >/dev/null 2>&1; then
																		name_editor="$1"
																	fi
																else
																	echo "Editor must have a name" >&2
																	exit 1
																fi
															fi
															;;

			*)											name_script="$1"
															;;
		esac
		shift
	done

	standard_use "$name_editor" "$name_script" "$name_copy" "${executed_ops["copy"]}"

	return
}

input_handle "$@"
exit

