#!/bin/bash

# Algorithm for making template of Bash scripts

cmd_use=vim

if [ $# -ne 0 ] && [ -n "$1" ]; then
    if [ -f "$1" ]; then
        $cmd_use "$1"
        exit
    fi
    echo -e "#!/bin/bash\n\n# $1\n\n" > "$1"
    chmod +x "$1"
    $cmd_use "$1"
else
    echo "Script must have a name."
fi
exit

